title: "Add tiles: text, text, text"
hero_image: images/banner.png
description: Add three text tiles with equal heights
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: "Add tiles: text, text, text"
