---
title: Ajouter des tuiles enveloppées avec du texte, du texte, du texte
hero_image: images/banner.png
description: Ajoute trois tuiles de texte avec la même hauteur
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Ajouter des tuiles enveloppées avec du texte, du texte, du texte
